seed: 1234
ignore_layers: [] # ["speaker_emb"]
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:80000"
  world_size: 1
path:
  ckpt_path: "./output/ckpt/RAVDESS"
  log_path: "./output/log/RAVDESS"
  result_path: "./output/result/RAVDESS"
optimizer:
  batch_size: 32
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 25000
loss:
  alpha: 0.1
  beta: 0.1